In [205]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.neighbors import NearestNeighbors, KNeighborsTransformer

### Towns recommended based on Jaccard similarity

Jaccard similarity is primarily used for calculating similarities between sets. It measures the similarity between finite sample sets by looking at what they have in common divided by their total combined elements. Mathematically, it's defined as the size of the intersection divided by the size of the union of the sets:

J(A,B) = |A ∩ B| / |A ∪ B|

For town recommendations, this is particularly useful when comparing binary or categorical features (like amenities, services, or attributes that towns either have or don't have). The score ranges from 0 (no similarity) to 1 (identical).

Unlike cosine similarity which works well with continuous numerical data, Jaccard similarity excels with binary/categorical data and is not concerned with the magnitude of features, only their presence or absence.

In [206]:
import os

# User selections
# List to store DataFrames for each user
user_choices = []

# Get all files from the user_output directory
user_files = os.listdir("../../data/user_output/")

# Read each file into a DataFrame and add to the list
for file in user_files:
    file_path = os.path.join("../../data/user_output/", file)
    user_df = pd.read_csv(file_path)
    user_choices.append(user_df)

df_pueblos = pd.read_csv("../../data/interim/pueblos_recommender.csv")

### We have to make sure to load the user choices from the same set of encoded towns.

In [207]:
user_choices

[   Unnamed: 0   cmun   province            municipality  altitude  longitude  \
 0        6618  29020     Málaga                 Arriate  596.1475  -5.140064
 1        2208   8258  Barcelona       Santa Maria d'Oló  515.0869   2.035291
 2        3568  44208     Teruel  Santa Cruz de Nogueras  888.4601  -1.088758
 3          45  48008    Bizkaia             Artzentales  245.3207  -3.241389
 4         254  39027  Cantabria       Campoo de Enmedio  878.4844  -4.150000

    latitude  0-17  18-24  25-34  ...  enc_75    enc_76    enc_77    enc_78  \
 0  36.79936   678    331    425  ...     0.0  1.841297  0.721064  1.336097
 1  41.87207   176     64     80  ...     0.0  0.284170  0.721064 -0.729801
 2  41.11458     0      0      1  ...     0.0 -0.883675 -1.242798  0.303148
 3  43.24055    97     26     58  ...     0.0  0.284170  0.721064 -0.213326
 4  42.96667   604    216    284  ...     0.0 -0.883675 -1.242798 -0.213326

      enc_79    enc_80    enc_81    enc_82    enc_83    enc_84
 0  2.559442  1.362170  0.789700  1.250591  1.527934  2.631339
 1  0.145342 -0.397119  1.480746  0.589951 -0.215439  0.153108
 2 -0.701119 -0.397119 -0.720799 -2.503028 -0.779248 -0.692881
 3 -0.128513 -0.397119  0.503125  0.260162 -0.376346 -0.134270
 4  2.276753  0.874541 -0.223207  0.713866  2.150024  2.240634

 [5 rows x 138 columns],
    Unnamed: 0   cmun   province            municipality  altitude  longitude  \
 0        5540  10021    Cáceres        Arroyo de la Luz  348.1518  -6.581785
 1        2801   8165  Barcelona  Pobla de Claramunt, La  272.2743   1.675936
 2        5356  16276     Cuenca                  Yémeda  866.7178  -1.723756
 3         540  24143       León                 Sancedo  685.0873  -6.632887
 4        5408  45174     Toledo                 Totanés  730.3002  -4.226097

    latitude  0-17  18-24  25-34  ...  enc_75    enc_76    enc_77    enc_78  \
 0  39.48631   701    333    559  ...     0.0  0.284170  0.721064  1.336097
 1  41.55298   445    190    263  ...     0.0  1.841297  0.721064 -0.213326
 2  39.76288     0      0      1  ...     0.0 -0.883675 -2.715694  1.336097
 3  42.66800    48     31     35  ...     1.0  1.062733 -0.260867  0.303148
 4  39.71007    45     25     47  ...     0.0 -0.105112 -1.242798 -0.471564

      enc_79    enc_80    enc_81    enc_82    enc_83    enc_84
 0  3.712684  3.886366  1.442361  0.484429  4.211411  3.792152
 1  1.171696  2.050587  3.224534  1.516148  0.433258  1.155702
 2 -0.705937 -0.397119 -0.660655 -2.349074 -0.752641 -0.697725
 3 -0.296359 -0.397119 -0.028426 -0.181733 -0.304128 -0.290875
 4 -0.417627 -0.397119  0.129679  0.483571 -0.470103 -0.400660

 [5 rows x 138 columns],
    Unnamed: 0   cmun     province              municipality    altitude  \
 0        5973   6143      Badajoz       Valverde de Leganés   291.00590
 1        5874   3026     Alicante                Beniarbeig    46.27847
 2        2864  40229      Segovia     Villaverde de Montejo  1043.89700
 3        5938  13020  Ciudad Real  Argamasilla de Calatrava   677.00890
 4        5013  10110      Cáceres          Losar de la Vera   533.01910

    longitude  latitude  0-17  18-24  25-34  ...  enc_75    enc_76    enc_77  \
 0  -6.981911  38.67241   720    366    489  ...     0.0 -0.105112  0.721064
 1  -0.002065  38.82312   410    173    240  ...     0.0  2.619860  0.721064
 2  -3.655480  41.52252     0      0      0  ...     1.0  0.284170 -0.260867
 3  -4.080076  38.72688   990    370    532  ...     0.0  2.619860 -2.715694
 4  -5.605157  40.12332   366    193    285  ...     0.0 -0.494394  0.721064

      enc_78    enc_79    enc_80    enc_81    enc_82    enc_83    enc_84
 0  0.303148  2.677497  1.314363  0.697648  1.262071  1.342954  2.731437
 1 -0.988038  1.243171  1.237872  1.260204  1.103687  0.902043  1.252570
 2 -0.988038 -0.703528 -0.397119 -0.656049 -2.738670 -0.705763 -0.692881
 3  0.819623  3.951203  3.398737  1.432071  0.946134  4.467342  3.964902
 4 -0.729801  1.534694  0.960593 -0.176016  0.531486  2.120884  1.520575

 [5 rows x 138 columns],
    Unnamed: 0   cmun province         municipality   altitude  longitude  \
 0        6290  21017   Huelva              Calañas   297.4208  -6.878683
 1        3197  42155    Soria  Retortillo de Soria  1241.5130  -2.980882
 2        2535  25189   Lleida             Rosselló   257.0000   0.595785
 3        2914  42020    Soria              Almazán   962.2736  -2.533437
 4        1471   9236   Burgos     Olmillos de Muñó   807.4762  -3.940343

    latitude  0-17  18-24  25-34  ...  enc_75    enc_76    enc_77    enc_78  \
 0  37.65482   451    166    290  ...     0.0 -0.494394  0.721064  1.336097
 1  41.31117     3      1      3  ...     1.0 -0.883675 -2.224728 -1.504513
 2  41.69844   645    244    383  ...     0.0  1.841297  0.721064  0.819623
 3  41.48592   892    373    587  ...     0.0 -0.883675  0.721064  0.819623
 4  42.20261     0      0      7  ...     1.0 -0.494394  0.721064  1.077860

      enc_79    enc_80    enc_81    enc_82    enc_83    enc_84
 0  1.493736 -0.014665 -0.211979  0.904596  1.316347  1.483442
 1 -0.615188 -0.397119 -0.712991 -2.638513 -0.200235 -0.623459
 2  1.972380  0.759805  0.144658  1.705855  0.943853  1.924195
 3  3.671726  5.100658  1.062401  0.790794  4.145528  3.593571
 4 -0.688269 -0.397119 -0.597510 -0.708373 -0.795719 -0.678351

 [5 rows x 138 columns],
    Unnamed: 0   cmun     province        municipality   altitude  longitude  \
 0        5975   2008     Albacete             Alcaraz   946.7922  -2.492647
 1        6454  18048      Granada             Cijuela   539.7335  -3.810801
 2        3624  19183  Guadalajara           Milmarcos  1061.3940  -1.876277
 3        5260  45037       Toledo  Carpio de Tajo, El   482.8380  -4.454660
 4        3582  28126       Madrid          Robregordo  1297.6080  -3.593292

    latitude  0-17  18-24  25-34  ...  enc_75    enc_76    enc_77    enc_78  \
 0  38.66966   176     93    120  ...     0.0 -0.883675  0.721064 -0.988038
 1  37.19989   840    289    513  ...     0.0  0.284170  0.721064  1.594334
 2  41.08623     5      2      4  ...     0.0 -0.883675 -1.242798 -0.471564
 3  39.88752   229    128    180  ...     0.0 -0.883675 -2.715694  0.819623
 4  41.10658     8      2      8  ...     1.0 -0.883675 -0.260867 -0.988038

      enc_79    enc_80    enc_81    enc_82    enc_83    enc_84
 0  0.330857  0.138317 -0.482420  0.436835  0.827291  0.308098
 1  2.274343  1.505590  1.453064  2.056595  1.553274  2.266466
 2 -0.664176 -0.397119 -0.683375 -0.386014 -0.585399 -0.660592
 3  0.781392  0.673753  0.374195  0.224167  1.094625  0.787599
 4 -0.661767 -0.397119 -0.684743  0.961371 -0.647481 -0.652519

 [5 rows x 138 columns],
    Unnamed: 0   cmun   province  municipality  altitude  longitude  latitude  \
 0        2909  50208   Zaragoza  Pina de Ebro  160.1591  -0.531969  41.48727
 1        1707   9430     Burgos   Villaespasa  960.8056  -3.402259  42.09895
 2        1590   8268  Barcelona         Cercs  749.4134   1.856175  42.15168
 3          64  48097    Bizkaia      Zaratamo  167.1853  -2.873626  43.21151
 4         450  31905    Navarra       Beriáin  499.5828  -1.645333  42.73380

    0-17  18-24  25-34  ...  enc_75    enc_76    enc_77    enc_78    enc_79  \
 0   399    215    275  ...     0.0 -0.883675  0.721064  1.077860  1.243171
 1     0      0      1  ...     1.0 -0.883675 -1.242798 -0.729801 -0.702725
 2   162     64    108  ...     0.0  1.841297  0.721064 -0.988038  0.237698
 3   239    123    171  ...     0.0  2.619860  0.721064  0.303148  0.570982
 4   792    356    460  ...     0.0  1.841297  0.721064  2.110809  2.645373

      enc_80    enc_81    enc_82    enc_83    enc_84
 0  0.817173  0.077518  1.070657  0.845028  1.236426
 1 -0.397119 -0.596346 -2.317084 -0.685491 -0.692881
 2  0.109633 -0.119469  0.336212  0.492806  0.240290
 3  1.161381  1.196679  1.013605  0.138050  0.580946
 4  2.911109  0.762454  1.527983  1.287207  2.734666

 [5 rows x 138 columns]]

In [208]:
df_pueblos

,Unnamed: 0,cmun,province,municipality,altitude,longitude,latitude,0-17,18-24,25-34,...,enc_75,enc_76,enc_77,enc_78,enc_79,enc_80,enc_81,enc_82,enc_83,enc_84
0,0,48067,Bizkaia,Muxika,18.95764,-2.692941,43.28967,302,96,101,...,0.0,1.062733,0.721064,-0.213326,0.521190,0.386912,1.185980,0.750134,0.143118,0.482462
1,1,15064,A Coruña,Paderne,151.44100,-8.176355,43.28677,265,119,160,...,1.0,0.284170,0.721064,2.110809,1.199804,0.731121,0.865604,-0.135614,0.767742,1.260643
2,2,15039,A Coruña,Irixoa,362.87660,-8.058925,43.28474,119,61,95,...,0.0,-0.105112,0.721064,1.077860,0.350131,-0.397119,0.279576,-0.236198,0.148186,0.371063
3,3,48062,Bizkaia,Mendata,107.88860,-2.633333,43.28333,58,28,32,...,0.0,0.284170,0.721064,-0.213326,-0.413611,-0.397119,0.994147,0.732753,-0.580331,-0.413576
4,4,48905,Bizkaia,Zamudio,44.55854,-2.866667,43.28333,528,226,291,...,0.0,2.619860,0.721064,0.819623,1.939453,6.343633,2.815453,0.890158,1.046479,1.977473
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6665,6665,29057,Málaga,Genalguacil,508.32510,-5.235879,36.54427,44,16,32,...,0.0,1.062733,0.721064,0.561385,-0.395943,-0.397119,1.096759,-0.174132,-0.097609,-0.374828
6666,6666,11025,Cádiz,Paterna de Rivera,125.97050,-5.866053,36.52333,966,460,630,...,0.0,-0.494394,0.721064,-0.729801,3.709472,2.413918,7.126529,1.572083,2.171563,3.574197
6667,6667,29056,Málaga,Gaucín,609.39610,-5.317524,36.51830,250,101,139,...,0.0,0.284170,0.721064,1.077860,0.558132,0.511210,1.842909,0.602008,0.915980,0.532511
6668,6668,11001,Cádiz,Alcalá de los Gazules,158.39630,-5.723718,36.46045,793,445,670,...,0.0,-0.883675,0.721064,-0.471564,3.480590,2.413918,3.239257,1.345819,3.476559,3.398218
6669,6669,11013,Cádiz,Castellar de la Frontera,30.78278,-5.419937,36.28621,540,225,366,...,0.0,1.841297,0.721064,2.110809,1.680857,0.444280,4.338877,1.366751,0.633442,1.744988

In [209]:
df_pueblos['cluster'].unique()

array([2, 4, 1, 3, 0])

In [ ]:
# Create a dictionary to store DataFrames for each cluster
clusters = {}
for cluster in df_pueblos['cluster'].unique():
    # Store the DataFrame with rows belonging to the current cluster
    clusters[f"cluster_{cluster}"] = df_pueblos[df_pueblos['cluster'] == cluster]

# Filter encoded features for each cluster
pueblo_clusters_encoded_features = {}
for cluster_name, cluster_df in clusters.items():
    pueblo_clusters_encoded_features[cluster_name] = cluster_df.filter(regex=r"^enc_", axis=1)

# Filter for encoded features which will be used in cells below
users_encoded_features = [df_user_choice.filter(regex=r"^enc_", axis=1) for df_user_choice in user_choices]

In [211]:
# Fixed Jaccard similarity calculation function
def calculate_jaccard_similarity(user_features, town_features):
    """
    Calculate Jaccard similarity between user preferences and town features
    
    Parameters:
    -----------
    user_features : pandas.Series or DataFrame row
        Binary features representing user preferences
    town_features : pandas.Series or DataFrame row
        Binary features representing town characteristics
        
    Returns:
    --------
    float
        Jaccard similarity score (0-1)
    """
    # Check if input is DataFrame or Series and handle accordingly
    if isinstance(user_features, pd.DataFrame):
        # Extract binary columns - only consider the first 16 encoded features
        # These are typically the binary encoded features
        user_binary = user_features.iloc[0, :16].astype(bool)
    else:
        # It's a Series
        user_binary = user_features.iloc[:16].astype(bool)
    
    # Same for town features
    if isinstance(town_features, pd.DataFrame):
        town_binary = town_features.iloc[0, :16].astype(bool)
    else:
        town_binary = town_features.iloc[:16].astype(bool)
    
    # Calculate intersection and union
    intersection = sum(user_binary & town_binary)
    union = sum(user_binary | town_binary)
    
    # Avoid division by zero
    if union == 0:
        return 0
    
    return intersection / union

# Create similarity profiles for each user
user_similarity_profiles = []

# For each user in user_encoded_features
for user_idx, user_features in enumerate(users_encoded_features):
    # Create a dictionary to store similarities for each cluster
    similarity_profile = {
        'user_idx': user_idx,
        'cluster_similarities': {}
    }
    
    # Calculate similarities to each cluster
    for cluster_name, cluster_features in pueblo_clusters_encoded_features.items():
        # List to store similarities to each town in the cluster
        town_similarities = []
        
        # Calculate similarity to each town in the cluster
        # Calculate similarity to each town in the cluster
        for idx, town_features in cluster_features.iterrows():
            similarity = calculate_jaccard_similarity(user_features, town_features)
            town_similarities.append({
                'town_idx': idx,
                'similarity': similarity,
                'cmun': df_pueblos.loc[idx, 'cmun'],
                'municipality': df_pueblos.loc[idx, 'municipality']
            })
        
        # Sort towns by similarity (descending)
        town_similarities.sort(key=lambda x: x['similarity'], reverse=True)
        
        # Get the top 5 most similar towns
        top_towns = town_similarities[:5]
        
        # Calculate average similarity to cluster
        avg_similarity = sum(item['similarity'] for item in town_similarities) / len(town_similarities)
        
        # Store in the profile
        similarity_profile['cluster_similarities'][cluster_name] = {
            'avg_similarity': avg_similarity,
            'top_towns': top_towns
        }
    
    # Determine the most similar cluster
    most_similar_cluster = max(
        similarity_profile['cluster_similarities'].items(),
        key=lambda x: x[1]['avg_similarity']
    )
    
    similarity_profile['best_cluster'] = {
        'name': most_similar_cluster[0],
        'avg_similarity': most_similar_cluster[1]['avg_similarity']
    }
    
    # Add to the list of profiles
    user_similarity_profiles.append(similarity_profile)

# Create a summary DataFrame of user preferences by cluster
user_cluster_preferences = pd.DataFrame(
    [[profile['cluster_similarities'][f'cluster_{c}']['avg_similarity'] 
      for c in df_pueblos['cluster'].unique()] 
     for profile in user_similarity_profiles],
    columns=[f'Cluster {c}' for c in df_pueblos['cluster'].unique()]
)

# display(user_similarity_profiles)

user_cluster_preferences['Best Cluster'] = [profile['best_cluster']['name'] for profile in user_similarity_profiles]
user_cluster_preferences.index = [f'User {i+1}' for i in range(len(user_cluster_preferences))]

# Display the summary
display(user_cluster_preferences)

user_cluster_preferences.shape

        Cluster 2  Cluster 4  Cluster 1  Cluster 3  Cluster 0 Best Cluster
User 1   0.000000   0.000000   0.000000   0.000000   0.000000    cluster_2
User 2   0.031558   0.017005   0.015351   0.000000   0.057154    cluster_0
User 3   0.055227   0.030085   0.039474   0.000000   0.011591    cluster_2
User 4   0.000000   0.000000   0.000000   0.000000   0.000000    cluster_2
User 5   0.020710   0.000654   0.010965   0.027374   0.007994    cluster_3
User 6   0.000000   0.000000   0.000000   0.000000   0.000000    cluster_2

(6, 6)